### ISSUE TITLE
Error with FLUENT_COMMENTS_EXCLUDE_FIELDS

### ISSUE THREAD

**Issue by wfehr** [django-fluent/django-fluent-comments#103]
The setting is shown like this in README.rst:
> FLUENT_COMMENTS_EXCLUDE_FIELDS = ('name', 'email', 'url')

Using it like this it causes me this error:
> Field name '{0}' in FLUENT_COMMENTS_EXCLUDE_FIELDS is invalid, it does not exist in the comment form.

It works if I am using a list instead of a tuple, i.e.
> FLUENT_COMMENTS_EXCLUDE_FIELDS = ['name', 'email', 'url']

So this is either an error in the README.rst or in your "appsettings.py".
There, the FLUENT_COMMENTS_FIELD_ORDER-setting uses `... = tuple(getattr(...` but EXLUDE_FIELDS doesn't use "tuple()".

**Comment by vdboor** [comment]
This should be working nowadays. I've fixed the error message to ease debugging
