### ISSUE TITLE
NoReverseMatch: 'comments-post-comment-ajax'

### ISSUE THREAD

**Issue by kvedes** [django-fluent/django-fluent-comments#104]
I'm using Django 1.11.3 in python 2.7.13 on Xubuntu 17.04. I have followed the steps described in the README:
1. pip install django-fluent-comments
2.  Added the following to settings:
INSTALLED_APPS += (
    'fluent_comments',  # must be before django_comments
    'crispy_forms',
    'django_comments',
    'django.contrib.sites',
)
CRISPY_TEMPLATE_PACK = 'bootstrap3'
COMMENTS_APP = 'fluent_comments'
3. Added this to urls.py:
urlpatterns += patterns('',
    url(r'^blog/comments/', include('fluent_comments.urls')),
)
4. Added these lines to my file blogpost.html:
{% load comments static %}

<link rel="stylesheet" type="text/css" href="{% static 'fluent_comments/css/ajaxcomments.css' %}" />
<script type="text/javascript" src="{% static 'fluent_comments/js/ajaxcomments.js' %}"></script>

{% render_comment_list for object %}
{% render_comment_form for object %}
5. Copied the folders fluent_comments/static/fluent_comments/ into my static folder
6. Run (my app is called blog)
python manage.py makemigrations blog
python manage.py migrate
python manage.py collectstatic
7. In my templates folder I have created a folder called comments and in that folder created a file called base with the following content:
{% extends base.html %}{% load i18n %}
{% block title_post %}{% block title %}{% trans Responses for page %}{% endblock %}{% endblock %}
{% block content %}
    <div id=comments-wrapper>
        {% block content %}{% endblock %}
    </div>
{% endblock %}
where title_post and content are tags that I use in the base.html for the whole site.

When I run the server and try to show a blog post (opening blogpost.html on the page) I get the following error:
NoReverseMatch at /blog/webscraping-apartments-copenhagen/
![pic](https://i.imgur.com/QCpz3lj.png)

**Comment by b2scrip** [comment]
i prefer this comment system.
[https://github.com/r26zhao/django-easy-comment](url)

**Comment by vdboor** [comment]
Hi!

The error implies that adding the `urls` didn't work properly. Can you check that it's really part of your site URL structure?
