### ISSUE TITLE
Incompatibility issue for Django 2.0

### ISSUE THREAD

**Issue by lmr2391** [django-fluent/django-fluent-comments#108]
In the `post_comment_ajax` view you're using the `is_authenticated` method on the `User` instance. This ability to call it as method and property was deprecated in Django 1.10 removed in 2.0: https://docs.djangoproject.com/en/2.0/releases/2.0/#features-removed-in-2-0

**Comment by lmr2391** [comment]
ok, I just saw there is already an PR but I couldn't find an issue

**Comment by vdboor** [comment]
Fixed! v2.0 is out!

**Comment by lmr2391** [comment]
Great, thanks! We're already running it in production :)
