### ISSUE TITLE
Akismet does not seem to see comments

### ISSUE THREAD

**Issue by quotaatypique** [django-fluent/django-fluent-comments#114]
Hi !

I'm very happy with this app, which I have installed lately on my blog --I was using django_comments before.
I enabled Akismet, entered my API key, made sure my comments were going through fluent_comments. I receive spam that is always moderated, but I don't see anything on the Akismet graph.
I know Akismet receives comment data to send back the info if it's spam or not, I think I should see numbers incrementing there...

Am I missing a parameter? How to debug this?

Thank you!

**Comment by vdboor** [comment]
Could you retry with the latest version? I've added some akismet fixes when the comments were associated with a different model. Also try enabling `DEBUG` logging in your `LOGGING` settings, to see whether the request is submitted to akismet.

You can also try the akismet tests: By default, Akismet will not report any post from the Django superuser as spam. Comments with the name "viagra-test-123" will always be flagged as spam.
