### ISSUE TITLE
Pip install cannot  Could not find a version that satisfies the requirement django-fluid-comments (from versions: ) No matching distribution found for django-fluid-comments

### ISSUE THREAD

**Issue by NomeChomsky** [django-fluent/django-fluent-comments#118]

**Comment by NomeChomsky** [comment]
Hi, when trying to do a pip install I get this:
 Could not find a version that satisfies the requirement django-fluid-comments (from versions: )
No matching distribution found for django-fluid-comments

**Comment by chris542** [comment]
@NomeChomsky It's not 'fluid'. It's 'fluent'
