### ISSUE TITLE
Convert ajaxcomments.js to jQuery plugin 

### ISSUE THREAD

**Issue by euanlau** [django-fluent/django-fluent-comments#23]
Have you considered rewriting the thing to a proper jQuery plugin?
Right now it is just a bunch functions in the global namespace. It would be nice to convert it to a configurable plugin.

**Comment by kim07** [comment]
thanks helped me a lot :)

**Comment by rosscdh** [comment]
Hi there! Any particular reason? The pic I built was fully functional?

**Comment by rosscdh** [comment]
Just re read the thread!
If required I can easily now make a PR!

Sorry for the long... Delay

**Comment by euanlau** [comment]
I haven't worked on this for a long time and I closed this simply due to the inactivity.

**Comment by rodolphopivetta** [comment]
Hey @rosscdh I'll appreciate very much your PR, if it's possible.

Thanks
