### ISSUE TITLE
with akismet moderation open, cannot publish a post with Chinese characters in the name field.

### ISSUE THREAD

**Issue by sanorchid** [django-fluent/django-fluent-comments#27]
when i submit a comment with Chinese characters in the user_name field, it goes with the "please wait ..." signal, but then nothing happens. 
i tried with English in the user_name field, it functioned as it supposed to.
when i closed the akismet (delete the akismet_api_key in the settings.py), it also worked. 
i cannot figure out where my app is wrong because i take actions exactly as your guide in the configuration page. 
if you have time, please help me check about this. thanks.

**Comment by vdboor** [comment]
Hi! sorry for not noticing this before. Does the issue still occur with the latest release? We've fixed a few things here and there.
