### ISSUE TITLE
Too much spam, even with Akismet

### ISSUE THREAD

**Issue by nickbewley** [django-fluent/django-fluent-comments#42]
I'm not sure what I have done wrong, but I get at least 5 spam comments per day, if not more. I followed the example project when setting it up. This is my `settings.py`:

```
INSTALLED_APPS = (
    'fluent_comments',
    'threadedcomments',
    'crispy_forms',
    'django.contrib.comments',
)

FLUENT_COMMENTS_EXCLUDE_FIELDS = ('url', 'title')
FLUENT_CONTENTS_USE_AKISMET = True          
COMMENTS_APP = 'fluent_comments'
FLUENT_COMMENTS_USE_EMAIL_MODERATION = True
FLUENT_COMMENTS_MODERATE_AFTER_DAYS = 7
FLUENT_COMMENTS_AKISMET_ACTION = 'moderate'
AKISMET_API_KEY = 'my-key' 
AKISMET_IS_TEST = False
```

The template is pretty standard:

```
{% load comments %}

{% get_comment_count for object as count  %}
   {% if count %}
      <div class='comments-title'>Comments on "{{ object.name }}":</div>
      <hr />
   {% else %}
      <div class='comments-none'>
         There are no comments yet.
      </div>
   {% endif %}

{% render_comment_list for object %}
{% render_comment_form for object %}
```

models.py:

```
from fluent_comments.moderation import moderate_model, comments_are_open, comments_are_moderated
from fluent_comments.models import get_comments_for_model, CommentsRelation

class Blog(models.Model):
    name = models.CharField(max_length=50)
    date = models.DateTimeField()
    slug = models.SlugField()
    ... etc...

moderate_model(
    Blog,
    publication_date_field='date',
    enable_comments_field='enable_comments'
)
```

Is this standard, or am I missing something? I have registered with Akismet, I have the correct Akismet api key in the settings, and I have Akismet 0.2.0 installed on the server (pypi). I'm on Django 1.4.2 with Fluent-comments 0.8.0 and Threaded-comments 0.9.0.

This is about 5 days worth of spam in my comments section:

![screen shot 2014-06-03 at 9 28 24 pm](https://cloud.githubusercontent.com/assets/5789940/3169635/4d300910-eba2-11e3-8363-db3249fc7295.png)

What to do? Also, the spam comments aren't deleted or moderated after the 7 day period set in the settings.py.. Thanks for any assistance!

**Comment by vdboor** [comment]
I've added `FLUENT_COMMENTS_AKISMET_ACTION=auto` and `FLUENT_COMMENTS_AKISMET_ACTION=delete` to remove spam.
