### ISSUE TITLE
Conficting error

### ISSUE THREAD

**Issue by Sonicmr** [django-fluent/django-fluent-comments#54]
I can't get the app to work. That's what is poping out when I try to runserver

*_RuntimeError: Conflicting 'fluentcomment' models in application 'fluent_comments' class fluent_comments.models.FluentComment and <class app.flucom.fluent_comments.models.FluentComment  *_

.

**Comment by vdboor** [comment]
Hi, what is the `app.flucom` part doing in your error? Is that a part of your application?
