### ISSUE TITLE
builtin django-threadedcomments outofdate

### ISSUE THREAD

**Issue by devbollinger** [django-fluent/django-fluent-comments#75]
Hi guys,

I was having an issue using threadedcomments, it seems that the one you guys used is 0.5 and it seems to be not working at least with django 1.8, the error was:

> from django.utils.encoding import force_unicode
> ImportError: cannot import name 'force_unicode'

When manually installing django-threadedcomments everythings went smooth. Is there a way to manualy remove the built in package of this apps ? I don,t want to have 2 of this package in my site-package

It will be nice to have at least a note about this issue

**Comment by vdboor** [comment]
> it seems that the one you guys used is 0.5
> When manually installing django-threadedcomments everythings went smooth.

I'm sorry, I don't really get what you mean. Do you have an example what you installed, or when things went wrong?
