### ISSUE TITLE
comment moderation not working

### ISSUE THREAD

**Issue by JRafiei** [django-fluent/django-fluent-comments#77]
Please forgive me if here is not the right place to ask this question, but i didn't find any answer on stackoverflow or similar sites. also maybe this is something related to code so ..
As far as i understand commenting framework use signals for moderation purposes. In django_comments.moderation.py module in connect method of Moderator class there are to signal listeners that act on signals sended by "django_comments.get_model()" which in this case is "fluent_comments.models.FluentComment". but when posting a comment using the post_comment view of django_comments.views.comments.py module, in the section of sending the signal, the sender is comment.**class** which resolves to "django_comments.models.Comment" and therefore the signal get  ignored(I guess!)
Any suggestion or clue where might be the source of problem?
I attach code snippets for convenience.
django_comments.moderations.py:
![moderation](https://cloud.githubusercontent.com/assets/13350419/13932092/2aeffe32-efc4-11e5-8b85-dad0e7b4c577.jpeg)

django_comments.views.comments.py:
![post](https://cloud.githubusercontent.com/assets/13350419/13932108/41e6c6f2-efc4-11e5-8563-fce4978cd1e3.jpeg)

**Comment by vdboor** [comment]
Good point! Maybe this is caused by the fact that the model is a proxy class.

Previously, there was no auto-moderation. Hence we require an explicit setup in the readme file: https://github.com/edoburu/django-fluent-comments#comment-moderation

**Comment by vdboor** [comment]
In the latest version, I've added a "default moderator" so all comments will receive moderation. The moderator registration is only needed to support things like "auto close/moderate after x days"
