### ISSUE TITLE
Captcha Validation

### ISSUE THREAD

**Issue by Sheepzez** [django-fluent/django-fluent-comments#78]
I'm getting a lot of spam on my site (Akismet is helping lots, but still some gets through), and I'd like to reduce the ability for bots to even post on the site, so I'd like to use Google' reCAPTCHA system. This involves adding an extra field to the form, and then doing a POST request server-side to check the key the client sent is valid.

@vdboor Do you have any suggestions on how to insert this functionality in the existing comments structure? Is it possible to add custom fields? And how would I go about doing the server-side POST (and marking as delete if it fails)?

I don't need a walkthrough, just a "here's where you would put this code"! :)

Thanks for any help in advance!

**Comment by vdboor** [comment]
@Sheepzez , yes you can add a custom form to achieve this.

The starting point would be redefining `COMMENTS_APP` to your own app, and when provide the `get_model()` and `get_form()` functions that we provide in `__init__.py`. If you let them extend our own form class, you can add a captcha there.

**Comment by vdboor** [comment]
Update, for version 1.3 there is a `FLUENT_COMMENTS_FORM_CLASS` setting that allows defining a custom form class. Captcha support however, is not added yet and requires updates in the JavaScript code to update on every Ajax post.

**Comment by Sheepzez** [comment]
Awesome, glad there's still progress being made on this. Would it be reasonable to just add that JavaScript code myself to my templates?

**Comment by vdboor** [comment]
Oh, yes, please! 👍 I'd love to have contributions and patches for this code.
You may find some inspiration for the captcha support in https://github.com/edoburu/fluentcms-contactform/tree/master/fluentcms_contactform/forms

**Comment by Sheepzez** [comment]
Would it be appropriate to add a project dependency on another module such as [django-recaptcha](https://github.com/praekelt/django-recaptcha)? That would avoid duplicating code, and taking on maintenance of the captcha feature.

**Comment by vdboor** [comment]
hmm I missed that comment. Yes, that is perfectly acceptable. You can add an extra module in `fluent_comments.forms`. See https://github.com/django-fluent/fluentcms-contactform/blob/master/fluentcms_contactform/forms/recaptcha.py how this can be done

**Comment by vdboor** [comment]
Heck, I've done so myself: a9db5364d7655d46873bfaf535a3982fb4673145

**Comment by petercollingridge** [comment]
I spent some time trying to get recaptcha to work, but eventually figured out (I think) that the version of django-fluent-comments on pypi doesn't yet include it. How can I get it to work with using pip install? I guess I just need to copy over the new forms, but maybe there's something else that needs to be updated too?

**Comment by vdboor** [comment]
Thanks for mentioning this! I've released v2.1
