### ISSUE TITLE
Question/Idea: Does flluent_comment allow a filtering of the uncersored words in the comments?

### ISSUE THREAD

**Issue by popovvasile** [django-fluent/django-fluent-comments#83]
How can I implement filtering the comments after identifying an uncensored word?

**Comment by vdboor** [comment]
You can look into the `CommentModerator` class. We've implemented an example using the `FluentCommentsModerator` class.. django-contrib-comments provides a framework to add moderation.

Also see: https://django-contrib-comments.readthedocs.io/en/latest/moderation.html

**Comment by vdboor** [comment]
I've added a `FLUENT_COMMENTS_MODERATE_BAD_WORDS` setting to the 1.4 release! You can use that now instead of having to reimplement a moderator.
