### ISSUE TITLE
Override list template

### ISSUE THREAD

**Issue by rodolphopivetta** [django-fluent/django-fluent-comments#93]
I'm trying to change the list template (i'm using threadedcomments) and I noted that the js script is much static with the labels and tags in the list.html template (that i'm trying to override).

Whats the best way to override this template?

**Comment by NogerbekNurzhan** [comment]
Do you found a solution?

**Comment by vdboor** [comment]
What is the kind of detail you'd like to override? Most likely you only need to override `comments/comment.html`.

You can copy-paste the `fluent_comments/templatetags/threaded_list.html` file for inspiration,
and create a file with a similar name in your project.
